### ISSUE TITLE
Track the 3.7 branch

### ISSUE THREAD

**Issue by serhiy-storchaka** [berkerpeksag/cpython-emailer-webhook#7]
It seems to me that commits in the 3.7 branch are not reported to python-checkins@python.org.

**Comment by berkerpeksag** [comment]
True, 3.7 is not listed in `ALLOWED_BRANCHES`: https://github.com/berkerpeksag/cpython-emailer-webhook/blob/03ef6f5a32485a1196b84af51c286e933fe5460c/mailer.py#L15

I will add it.

**Comment by berkerpeksag** [comment]
Deployed. Let me know if you still don't see logs from the 3.7 branch in an hour or so. Thanks for the report!
